# docker-compose.yml
version: '3'
services:
  r510-denoiser:
    image: ghcr.io/dbeltman/r510-denoiser:master
    environment: 
      - MQTTHOST=MQTT-Server
      - FANNAME=TESTFAN
    devices:
        - "/dev/ipmi0:/dev/ipmi0"
