# docker-compose.yml
version: '3'
services:
  r510-denoiser:
    image: dockerdaan:r510-denoiser:latest
    environment: 
      - MQTTHOST=MQTT-Server
      - FANNAME=TESTFAN
    devices:
        - "/dev/ipmi0:/dev/ipmi0"
