# docker-compose.yml
version: '3'
services:
  flask:
    image: dockerdaan/denoiser-flask
    volumes:
      - "./:/app"
  nginx:
    image: dockerdaan/denoiser-nginx
    ports:
      - 5050:80
    depends_on:
      - flask